# Generated by Django 6.1.1 on 2026-09-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام قسط')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ کل قسط')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ هر قسط ماهانه')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداخت شده')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مانده بدهی')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
            },
        ),
    ]
