# Generated by Django 6.1.1 on 2026-09-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='monthly_amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ هر قسط ماهانه (تومان)'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ پرداخت شده (تومان)'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مانده بدهی (تومان)'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ کل قسط (تومان)'),
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('comment', models.TextField(blank=True, verbose_name='توضیحات')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='installments.installment', verbose_name='قسط')),
            ],
            options={
                'verbose_name': 'پرداخت قسط',
                'verbose_name_plural': 'پرداخت\u200cهای اقساط',
                'ordering': ['payment_date'],
            },
        ),
    ]
