# Generated by Django 6.1.1 on 2026-09-13 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0003_alter_installment_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='last_overdue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تاریخ معوقه'),
        ),
        migrations.AddField(
            model_name='installment',
            name='overdue_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد ماه\u200cهای معوقه'),
        ),
        migrations.CreateModel(
            name='InstallmentOverdue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='ماه سررسید')),
                ('marked_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('reason', models.TextField(blank=True, verbose_name='علت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='حل شده')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdues', to='installments.installment', verbose_name='قسط')),
            ],
            options={
                'verbose_name': 'قسط معوقه',
                'verbose_name_plural': 'اقساط معوقه',
                'ordering': ['-due_date'],
                'constraints': [models.UniqueConstraint(fields=('installment', 'due_date'), name='unique_installment_overdue_month')],
            },
        ),
    ]
