# Generated by Django 6.1.1 on 2026-09-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installments', '0004_installment_last_overdue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
    ]
