# Generated by Django 6.1.1 on 2026-09-13 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'واریز'), ('withdraw', 'برداشت')], max_length=10, verbose_name='نوع')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('comment', models.TextField(blank=True, verbose_name='توضیحات')),
                ('balance_after', models.IntegerField(verbose_name='موجودی پس از تراکنش')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-timestamp'],
            },
        ),
    ]
